# Generated by Django 3.2.4 on 2021-06-22 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_cliente', models.CharField(max_length=50)),
                ('empresa', models.CharField(max_length=50)),
                ('nom_cliente', models.CharField(max_length=50)),
                ('ape_cliente', models.CharField(max_length=50)),
                ('puesto', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('poblacion', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('cp', models.CharField(max_length=50)),
                ('numero_cc', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_pedido', models.CharField(max_length=50)),
                ('numero_pedido', models.CharField(max_length=50)),
                ('codigo_producto', models.CharField(max_length=50)),
                ('codigo_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd_basics.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=50)),
                ('descripcion_producto', models.CharField(max_length=50)),
                ('codigo_proveedor', models.CharField(max_length=50)),
                ('precio_unidad', models.CharField(max_length=50)),
                ('unidad_existente', models.CharField(max_length=50)),
                ('codigo_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bd_basics.pedidos')),
            ],
        ),
    ]
